name: login
description: This package contains the theme, resources (dimensions, colors), assets and base widgets (this widgets are not related to any entity, they are almost raw widgets such as a button) to use in the app.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  ui:
    path: ../../core/ui
  locale:
    path: ../../core/locale
  icons:
    path: ../../core/icons
  url_launcher: ^6.1.10
  freezed_annotation: ^2.2.0
  dio: ^5.3.3
  retrofit: ^4.0.1
  logger: any
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  freezed: ^2.3.2
  json_serializable: ^6.7.1
  retrofit_generator: any

flutter:
  assets:
    - assets/images/
