name: di
description: This package exports main classes and utilities around GetIt and general dependency injection that will be used in almost every package.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  base_redux:
    path: ../../core/base_redux

  get_it: ^7.2.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  build_runner: ^2.3.3
  mockito: ^5.3.2
  test_cov_console: ^0.2.2

flutter:
