name: ai_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^7.0.0
  dio: ^5.3.3
  ui:
    path: ../../core/ui
  locale:
    path: ../../core/locale
  splash:
    path: ../../base/splash
  signup:
    path: ../../base/signup
  login:
    path: ../../base/login
  profile:
    path: ../../base/profile
  home:
    path: ../../base/home

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true